### ISSUE TITLE
Update to latest Grails v3.3.5 (and GORM)

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-core#24]
We are currently on 3.3.1 across hoist-core and active projects. No pressing / urgent fixes we need to take here, but I would like to stay current-ish with the point releases to pick up any security or other bug fixes and avoid a bigger jump for when we really do want to upgrade.

At its simplest, this should be a matter of updating the versions within `gradle.properties`. If any problems or hangups, we can discuss and postpone or work through depending on the issue.

Grails releases tracked @ https://github.com/grails/grails-core/releases and GORM @ https://github.com/grails/gorm-hibernate5/releases.

**Comment by amcclain** [comment]
This is a bit of a higher priority as 3.3.2 included a fix to pathingJar support in the gradle plugin that we would like to take to help out with issues on Windows with overly long classpaths on developer machines.

**Comment by cnrudd** [comment]
starting on this with piq-react

**Comment by cnrudd** [comment]
this is done.
