### ISSUE TITLE
Unwind multi-environment config concept

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-core#30]
In practice we are finding the concept of each database instance holding all the config values across all environments more confusing than valuable.  It's difficult to grok and increases the chances for errors / confusion / incorrect entries.

This works in an environment with a strong notion of a master production DB that is constantly replicated to the secondary environments, but that's not an especially standard pattern. Where that does not exist, it would be far cleaner to have a single config value that if need be is different in the different env. databases.  The new config sync tool can help to compare, but will be simplified by virtue of comparing just the one field.

(Could consider if it's worth making this an optional mode and still supporting the current setup....)

**Comment by lbwexler** [comment]
Hi -- I think we should go ahead and do this now.  Let's tear down the existing multiple enviro database:

We should introduce a new 'value' column.  Prior to release to an environment, we can pre-populate the column with a bulk sql insert.   Following release, we can go ahead and wack the other prodValue/stageValue/betaValue etc...

**Comment by cnrudd** [comment]
Steps to migrate to this new config world:
Pull latest code.
Do not run app.
Run following SQL on app DB:  (below is MySql, may be slightly different for MS SQL Server)
Run app.

SQL to add value column:
`alter table xh_config
  add value longtext not null;`

SQL to copy all prod values to new 'value' column:
`UPDATE xh_config SET value = prod_value`

SQL for dropping old columns
```alter table xh_config
  drop column prod_value;

alter table xh_config
  drop column beta_value;

alter table xh_config
  drop column stage_value;

alter table xh_config
  drop column dev_value;```

**Comment by lbwexler** [comment]
Colin -- this is great.  As ATM pointed out, would like to do this in a two step process, so we can smoothly release without extra downtime risk.

Can we modify so that the first step creates and populates the new column?  The second step can delete the obsolete columns, and can be done after the new app is safely up and running.

I don't think we will be able to insert configs until we drop the columns (due to the non-null constraint on prod_value) but that should be fine -- we don't need to create new configs right away in any case!

**Comment by cnrudd** [comment]
I tested the new code with the config differ.  Works very well.  no changes required to the differ, that I can see.

**Comment by cnrudd** [comment]
@lbwexler 
this new behaviour "The required configuration keys will be added automatically on first run to a DB that doesn’t have them, but the roles config will of course need to be populated with the correct set of users."  may require that the old columns be dropped before the app is up and running.

**Comment by cnrudd** [comment]
Or maybe we can add some SQL to scripts above to change prod_value to allow null.

**Comment by lbwexler** [comment]
sounds good

**Comment by cnrudd** [comment]
The all migration code above has been updated to have the pros_value column allow null.

**Comment by cnrudd** [comment]
The last remaining issue on this ticket is that I have found that the 'apply diff' context menu button in the differ only captures one record, even when a user has selected multiple rows.  This appears to be an issue with how our context menu uses the params passed by ag grid.

**Comment by lbwexler** [comment]
Closing this for clarity, as this has been merged into the latest version of Hoist.  Look forward to rolling it out to all client applications.... 🌮
