### ISSUE TITLE
EmailService does not insert @ when relying on xhEmailDefaultDomain

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-core#43]
I would expect a standard `xhEmailDefaultDomain` config entry to just be e.g. `company.com` and not `@company.com` but the current implementation of `EmailService.formatAddresses()` relies on the config containing the @ sign.

We should fix but also review current live apps and their configs - one client production app has the @ in their config and we would need to coordinate upgrade.

**Comment by amcclain** [comment]
Note when we fix we will also want to revert 4594d2cf42814c1b82b452fdbc2465a7f98e0af2

**Comment by lbwexler** [comment]
👍

**Comment by lbwexler** [comment]
Just for the record, Don closed this by allowing the @ to be optionally present.  Its a clever variant, that eases the release of this change with almost zero cost.

We should go ahead and try to clean these up in all client installation nevertheless, as soon as Don's code is released.  Going forward, don't think anyone will think to add the '@'....

We'll add a comment now to the configs, to remember to clean them up
