### ISSUE TITLE
Client admin app asking for archived log spams log with stack trace

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-core#47]
A client app in hoist-sencha was left with the admin viewer looking at a log that then became archived..  This spammed the app log with "file not found" exceptions every 10 seconds until the user left the tab or refreshed!

(This is especially easy to do in hoist-sencha, where we select the *oldest* log by default.)

Admittedly a super corner case, but would be nice to just quietly hand back an empty log, or throw a client exception without spamming the server log.

**Comment by amcclain** [comment]
Weird that we are selecting the oldest log - sounds like that bit of code to select `[appCode].log` didn't make it to hoist-sencha, but would be worth adding there.

(That said, of course still want to avoid these repeated and not-helpful exceptions in the logs)
