### ISSUE TITLE
UAT AppEnvironment

### ISSUE THREAD

**Issue by haynesjm42** [exhi/hoist-core#63]
The standard environment names for at least one of our clients is:
* Dev/Staging (sometimes separate, sometimes synonymous)
* UAT
* Production

A developer at a client was asking how to get UAT to show up in the tab title for a hoist-react app and tried setting the `environment` to UAT in the instance config, but since it is not a recognized values in the enumeration it falls back to Development.

We have a Beta environment, which we could just rename as UAT if we aren't using that elsewhere, or we could just add UAT as a new entry.

Another question I would ask is whether we really need to be so restrictive with these environment names? Seems like we only really use this value to determine if we are in Production or not, otherwise it is just used for display purposes or provided for application-specific logic (though I may have missed something in my searches). Being more flexible could also be useful if there are multiple nodes behind a load balancer, so you could have UAT1, UAT2, etc. which can sometimes be useful for debugging.

**Comment by amcclain** [comment]
These enums had a much bigger impact within the framework when our config system was keyed off of them - with a value column-per-environment. We're not doing that anymore, of course, and could revisit.

There might still be value, however, in providing reliable ways for the framework to at least identify production vs. other environments....  Making it entirely flexible could have some downsides in that way.

To the point about the load balancer - also need to consider how this is loaded and displayed in the client app.

But I don't want these points to block any changes. One option would be to simply add `AppEnvironment` enum values for UAT as well as (long-requested) BCP (aka DR).  That might buy us time to revisit this in the context of larger Hoist plans around the server-side and a more centralized set of services.

(If we do, we should assign these to some reasonable colors within the client-side toolkit - don't necessarily need to be unique.)
