### ISSUE TITLE
Broken GString JSON serialization via Jackson

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-core#87]
Attempting to output e.g. a collection of GStrings via `renderJSON()` and our default Jackson serializer returns e.g.

```
[
  {
    "values": [
      1
    ],
    "strings": [
      "Message #",
      " here"
    ],
    "bytes": "TWVzc2FnZSAjMSBoZXJl",
    "valueCount": 1
  },
  {
    "values": [
      2
    ],
    "strings": [
      "Message #",
      " here"
    ],
    "bytes": "TWVzc2FnZSAjMiBoZXJl",
    "valueCount": 1
  },
  {
    "values": [
      3
    ],
    "strings": [
      "Message #",
      " here"
    ],
    "bytes": "TWVzc2FnZSAjMyBoZXJl",
    "valueCount": 1
  }
]
```

😮 

Looks like we will need to register a custom serializer, unless there is a better default behavior we could be specifying.

**Comment by lbwexler** [comment]
We can of course improve and look for more general/broader fixes, but this is well-worth taking right now.
